# Generated by Django 4.0.3 on 2022-03-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocompany', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carpart',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='carpart',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
