# Generated by Django 4.0.3 on 2022-03-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocompany', '0003_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpart',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
