# Generated by Django 4.0.3 on 2022-03-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocompany', '0005_remove_shoppingcart_items_shoppingcartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='delivery_datetime',
            new_name='ordered_date',
        ),
        migrations.RenameField(
            model_name='shoppingcartitem',
            old_name='product',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='total_items',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(to='autocompany.shoppingcartitem'),
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
