# Generated by Django 4.0.3 on 2022-03-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocompany', '0006_rename_delivery_datetime_shoppingcart_ordered_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='Order',
        ),
    ]
