# Generated by Django 4.0.3 on 2022-03-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocompany', '0008_rename_ordered_date_order_delivery_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcartitem',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='ordered',
        ),
    ]
