# Generated by Django 4.0.3 on 2022-03-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocompany', '0009_rename_item_shoppingcartitem_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcartitem',
            old_name='item_id',
            new_name='item',
        ),
    ]
